/**
 * @file priceExtractor.js
 * @description Extracts and reconciles price, MRP, discount, and stock status from a rendered product page.
 *
 * REASONING & DEFENSIVE DESIGN:
 * 1. Resilient Heuristics vs Obfuscated CSS:
 *    The store uses /api/products/:id/layout to inject rotating obfuscated class names
 *    (e.g., .c_9z2f, .layout_v4_p), making hardcoded CSS selectors fragile. Instead, we
 *    traverse nodes matching semantic and visual text patterns (/^₹[\d,]+/).
 *
 * 2. innerText() vs textContent():
 *    The store uses "priceCarrier": "split", distributing price digits across DOM nodes with CSS
 *    flex/grid 'order' properties or visual coordinate positioning. Calling element.textContent()
 *    retrieves raw DOM tree order (scrambled). Calling locator.innerText() forces Chromium's layout
 *    engine to compute the visual rendered text as seen by human users.
 *
 * 3. Struck-Through Exclusion (Decoy vs True Price):
 *    The page renders a decoy "deal price" and MRP alongside the true price. The decoy or original
 *    price is styled with line-through (via CSS text-decoration, text-decoration-line: line-through, or
 *    <del>/<s>/class annotations). Struck-through elements are explicitly filtered out using
 *    computed styles.
 *
 * 4. Reconciliation against MRP and Discount%:
 *    The true price satisfies: |Price - (MRP * (1 - Discount/100))| <= ₹2 tolerance.
 *    Decoy prices fail this check. If reconciliation succeeds, reconciled = true.
 */

/**
 * Normalises raw stock text into the standard enum.
 *
 * @param {string|null} text
 * @returns {'in_stock' | 'low_stock' | 'out_of_stock' | 'unknown'}
 */
export function normalizeStockStatus(text) {
  if (!text) return 'unknown';
  const clean = text.toLowerCase().trim();

  if (
    clean.includes('out of stock') ||
    clean.includes('sold out') ||
    clean.includes('currently unavailable') ||
    clean.includes('not in stock')
  ) {
    return 'out_of_stock';
  }

  if (
    clean.includes('low stock') ||
    clean.includes('few left') ||
    clean.includes('few units left') ||
    (clean.includes('only') && clean.includes('left')) ||
    clean.includes('hurry')
  ) {
    return 'low_stock';
  }

  if (
    clean.includes('in stock') ||
    clean.includes('available') ||
    clean.includes('ready to ship') ||
    clean.includes('in-stock')
  ) {
    return 'in_stock';
  }

  return 'unknown';
}

/**
 * Extracts numeric units remaining from raw stock candidate string.
 * Supports patterns like "In stock · 50 left", "Only 12 left", "25 in stock", "Selling fast — 8 left", "30 units left".
 *
 * @param {string|null} text
 * @returns {number|null}
 */
export function extractStockUnits(text) {
  if (!text) return null;
  const clean = String(text).trim();
  const match =
    clean.match(/(\d+)\s*(?:units?\s*)?left\b/i) ||
    clean.match(/(\d+)\s*in\s*stock\b/i) ||
    clean.match(/(?:only|hurry,?\s*just|selling\s*fast\s*[—–-])\s*(\d+)/i) ||
    clean.match(/(\d+)\s*(?:units?|pieces?|items?)\b/i);

  if (match) {
    const val = parseInt(match[1], 10);
    return isNaN(val) ? null : val;
  }
  return null;
}

/**
 * Clean numeric string into a float. Strips currency symbols, commas, and any inter-digit
 * whitespace or newlines generated by split DOM containers.
 *
 * @param {string|null} str
 * @returns {number|null}
 */
export function cleanNumber(str) {
  if (!str) return null;
  let clean = String(str)
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/[\s\r\n]+/g, '');

  // Handle European format from storefront: e.g. 18.601,00 or 18.601
  if (/,\d{2}$/.test(clean)) {
    // Comma decimal (e.g. 18.601,00) -> remove decimal part and period separators
    clean = clean.replace(/,\d{2}$/, '').replace(/\./g, '');
  } else if (/\.\d{3}$/.test(clean) && !/\.\d{2}$/.test(clean)) {
    // Period used as thousand separator in whole Indian rupees (e.g. 18.601)
    clean = clean.replace(/\./g, '');
  }

  // Remove commas and extract number
  clean = clean.replace(/,/g, '');
  const match = clean.match(/[0-9]+(?:\.[0-9]+)?/);
  if (!match) return null;
  const num = parseFloat(match[0]);
  return Number.isNaN(num) ? null : num;
}

/**
 * Extracts and reconciles pricing and stock information from a rendered Playwright Page.
 *
 * @param {import('playwright').Page} page - Active Playwright page with rendered DOM
 * @returns {Promise<{
 *   price: number | null,
 *   mrp: number | null,
 *   discountPercent: number | null,
 *   stockStatus: 'in_stock' | 'low_stock' | 'out_of_stock' | 'unknown',
 *   reconciled: boolean,
 *   rawTexts: {
 *     priceCandidates: string[],
 *     struckThroughCandidates: string[],
 *     mrpText: string | null,
 *     discountText: string | null,
 *     stockText: string | null
 *   }
 * }>}
 */
export async function extractFromPage(page) {
  const extractionResult = await page.evaluate(() => {
    const strikePattern = /(strike|line-?through|linethrough|del|decoy|old-?price|crossed|original-?price)/i;

    /**
     * Checks whether an element or any of its ancestors has line-through text-decoration,
     * strikethrough tag, or decoy markers.
     */
    function isElementOrAncestorStruck(el) {
      let curr = el;
      while (curr && curr !== document.body && curr !== document.documentElement) {
        if (curr.tagName === 'DEL' || curr.tagName === 'S' || curr.tagName === 'STRIKE') {
          return true;
        }
        if (
          strikePattern.test(curr.className || '') ||
          curr.getAttribute('data-decoy') === 'true' ||
          curr.getAttribute('aria-hidden') === 'true'
        ) {
          return true;
        }
        const style = window.getComputedStyle(curr);
        const decor = (style.textDecorationLine || style.textDecoration || '').toLowerCase();
        if (decor.includes('line-through')) {
          return true;
        }
        curr = curr.parentElement;
      }
      return false;
    }

    /**
     * Hostile defense check: Checks whether an element, any ancestor, OR ANY DESCENDANT
     * is struck-through or marked as a decoy.
     */
    function isStruckThrough(el) {
      if (isElementOrAncestorStruck(el)) {
        return true;
      }

      // Check if any descendant node is struck through
      if (el.children && el.children.length > 0) {
        const descendants = el.querySelectorAll('*');
        for (const desc of descendants) {
          if (desc.tagName === 'DEL' || desc.tagName === 'S' || desc.tagName === 'STRIKE') {
            return true;
          }
          if (strikePattern.test(desc.className || '') || desc.getAttribute('data-decoy') === 'true') {
            return true;
          }
          const descStyle = window.getComputedStyle(desc);
          const descDecor = (descStyle.textDecorationLine || descStyle.textDecoration || '').toLowerCase();
          if (descDecor.includes('line-through')) {
            return true;
          }
        }
      }

      return false;
    }

    /**
     * Checks if an element specifically has MRP labeling in its direct text or immediate badge parent.
     */
    function hasMrpContext(el) {
      const text = (el.innerText || '').toUpperCase();
      if (text.includes('MRP')) return true;
      const parent = el.parentElement;
      if (parent && parent !== document.body && parent !== document.documentElement) {
        const parentText = (parent.innerText || '').toUpperCase();
        if (parentText.length < 60 && parentText.includes('MRP')) {
          return true;
        }
      }
      return false;
    }

    const ignoreTags = new Set(['HTML', 'HEAD', 'BODY', 'SCRIPT', 'STYLE', 'MAIN', 'SECTION', 'ARTICLE', 'FORM']);
    const allElements = Array.from(document.querySelectorAll('*')).filter(
      (el) => !ignoreTags.has(el.tagName)
    );

    let mrpCandidateText = null;
    let stockCandidateText = null;
    const discountCandidates = [];
    const struckThroughCandidates = [];
    const struckElements = [];
    const rawPriceNodes = [];

    // Prioritize scanning .price-block for discount% first
    const priceBlock = document.querySelector('.price-block');
    if (priceBlock) {
      const pbElements = Array.from(priceBlock.querySelectorAll('*'));
      for (const el of pbElements) {
        if (el.children.length === 0 && el.textContent) {
          const text = (el.innerText || el.textContent).trim();
          if (!isStruckThrough(el)) {
            const discountMatch = text.match(/(\d{1,2}(?:\.\d{1,2})?)\s*%\s*(?:off|discount|save)?/i);
            if (discountMatch) {
              discountCandidates.push(discountMatch[1]);
            }
          }
        }
      }
    }

    // Prioritize checking .stock-badge directly for precise stock text.
    // NOTE: Out of stock badges are styled with text-decoration: line-through,
    // so we must NEVER filter them out with isStruckThrough!
    const stockBadgeEl = document.querySelector('.stock-badge');
    if (stockBadgeEl) {
      stockCandidateText = (stockBadgeEl.innerText || stockBadgeEl.textContent || '').trim();
      if (
        stockBadgeEl.classList.contains('out-stock') ||
        /out[-\s]?of[-\s]?stock|sold\s*out/i.test(stockCandidateText)
      ) {
        stockCandidateText = 'Out of stock';
      }
    }

    // 1. Scan for remaining Discount% and Stock Status across non-struck elements
    for (const el of allElements) {
      if (el.children.length === 0 && el.textContent) {
        const text = (el.innerText || el.textContent).trim();
        const struck = isStruckThrough(el);

        // General discount detection fallback
        if (!struck) {
          const discountMatch = text.match(/(\d{1,2}(?:\.\d{1,2})?)\s*%\s*(?:off|discount|save)?/i);
          if (discountMatch && !discountCandidates.includes(discountMatch[1])) {
            discountCandidates.push(discountMatch[1]);
          }
        }

        // Stock status detection fallback (exclude long fineprint paragraphs)
        if (!stockCandidateText && text.length <= 60) {
          const lower = text.toLowerCase();
          if (lower.includes('out of stock') || lower.includes('sold out')) {
            stockCandidateText = 'Out of stock';
          } else if (
            !struck &&
            !lower.includes('delivery estimates') &&
            !lower.includes('assume') &&
            (
              lower.includes('stock') ||
              lower.includes('available') ||
              lower.includes('units left') ||
              /\b\d+\s*left\b/i.test(lower) ||
              /\bonly\s*\d+\b/i.test(lower) ||
              /\bhurry\b/i.test(lower)
            )
          ) {
            stockCandidateText = text;
          }
        }
      }
    }

    // 2. Scan for price candidates (nodes starting with ₹ or containing currency)
    for (const el of allElements) {
      const text = (el.innerText || '').trim();
      const clean = text.replace(/[\u200B-\u200D\uFEFF]/g, '');
      const compacted = clean.replace(/[\s\r\n]+/g, '');

      if (/^₹[\d,]+/.test(compacted)) {
        const struck = isStruckThrough(el);
        const isMrp = hasMrpContext(el);

        if (isMrp) {
          mrpCandidateText = text;
          struckThroughCandidates.push(text);
          struckElements.push(el);
        } else if (struck) {
          struckThroughCandidates.push(text);
          struckElements.push(el);
        } else {
          rawPriceNodes.push({
            el,
            text,
            compacted,
            fontSize: parseFloat(window.getComputedStyle(el).fontSize) || 16,
          });
        }
      }
    }

    // Secondary defense: Purge any rawPriceNode that wraps or contains any element identified as struck
    const cleanPriceNodes = rawPriceNodes.filter((node) => {
      const containsStruck = struckElements.some((struckEl) => node.el.contains(struckEl));
      if (containsStruck) {
        struckThroughCandidates.push(node.text);
        return false;
      }
      return true;
    });

    // Filter out inner children when parent container also matches /^₹/
    // This retains the topmost container that assembled the full split digits
    const topContainers = cleanPriceNodes.filter((node) => {
      const hasParentContainer = cleanPriceNodes.some(
        (other) => other.el !== node.el && other.el.contains(node.el)
      );
      return !hasParentContainer;
    });

    return {
      priceCandidates: topContainers.map((c) => ({
        text: c.compacted,
        fontSize: c.fontSize,
      })),
      struckThroughCandidates,
      mrpCandidateText,
      discountCandidates,
      stockCandidateText,
    };
  });

  // Parse MRP — prefer an explicit "MRP" label, but always fall back to the
  // LARGEST struck-through ₹ value. On this store the MRP span is purely
  // "₹35,219" (struck through) with no label text — the largest struck value
  // is always the original full price (never a deal sub-price).
  let parsedMrp = null;
  if (extractionResult.mrpCandidateText) {
    parsedMrp = cleanNumber(extractionResult.mrpCandidateText);
  }
  for (const st of extractionResult.struckThroughCandidates) {
    const num = cleanNumber(st);
    if (num !== null && (parsedMrp === null || num > parsedMrp)) {
      parsedMrp = num;
    }
  }

  // Parse candidate discounts
  const parsedDiscounts = (extractionResult.discountCandidates || [])
    .map((d) => cleanNumber(d))
    .filter((d) => d !== null && d > 0 && d < 100);

  let parsedDiscount = parsedDiscounts.length > 0 ? parsedDiscounts[0] : null;

  // Parse candidate prices (ignoring duplicates)
  const candidateNumbers = [];
  for (const cand of extractionResult.priceCandidates) {
    const num = cleanNumber(cand.text);
    if (num !== null && num > 0 && !candidateNumbers.some((c) => c.price === num)) {
      candidateNumbers.push({
        price: num,
        text: cand.text,
        fontSize: cand.fontSize,
      });
    }
  }


  // Simple candidate selection: largest font-size wins (most prominent price on page).
  // If font sizes are equal, pick the largest value that is still under MRP (if known).
  // No reconciliation math — whatever the DOM shows at the biggest font is the sale price.
  let selectedCandidate = null;

  if (candidateNumbers.length > 0) {
    candidateNumbers.sort((a, b) => {
      // Prefer prices that are <= MRP (avoids picking an erroneously large DOM value)
      if (parsedMrp !== null) {
        const aUnder = a.price <= parsedMrp ? 1 : 0;
        const bUnder = b.price <= parsedMrp ? 1 : 0;
        if (aUnder !== bUnder) return bUnder - aUnder;
      }
      // Then largest font size
      if (b.fontSize !== a.fontSize) return b.fontSize - a.fontSize;
      // Then largest price value as tiebreak
      return b.price - a.price;
    });
    selectedCandidate = candidateNumbers[0];
  }

  const parsedPrice = selectedCandidate ? selectedCandidate.price : null;

  // Calculate discount from MRP if not scraped from page
  if (parsedPrice !== null && parsedMrp !== null && parsedDiscount === null && parsedPrice < parsedMrp) {
    parsedDiscount = Math.round((1 - parsedPrice / parsedMrp) * 100);
  }

  // Normalise stock status & units
  let stockStatus = normalizeStockStatus(extractionResult.stockCandidateText);
  if (stockStatus === 'unknown' && parsedPrice !== null && parsedPrice > 0) {
    stockStatus = 'in_stock';
  }
  const stockUnits = extractStockUnits(extractionResult.stockCandidateText);

  return {
    price: parsedPrice,
    mrp: parsedMrp,
    discountPercent: parsedDiscount,
    stockStatus,
    stockUnits,
    stockText: extractionResult.stockCandidateText || null,
    reconciled: parsedPrice !== null && parsedPrice > 0, // always true when a price is found
    rawTexts: {
      priceCandidates: candidateNumbers.map((c) => c.text),
      struckThroughCandidates: extractionResult.struckThroughCandidates,
      mrpText: extractionResult.mrpCandidateText,
      discountText: parsedDiscount !== null ? String(parsedDiscount) : null,
      stockText: extractionResult.stockCandidateText,
    },
  };
}

export default {
  extractFromPage,
  normalizeStockStatus,
  extractStockUnits,
  cleanNumber,
};

